# EJERCICIO 1

In [35]:
import numpy as np
import math
def raices(a,b,c):
    d=math.pow(b,2)-4*a*c
    if d < 0:
        z=abs(d)
        r1=(-b+math.sqrt(z)*1j)/(2*a)
        r2=(-b-math.sqrt(z)*1j)/(2*a)
    else:
        r1=(-b+math.sqrt(d))/(2*a)
        r2=(-b-math.sqrt(d))/(2*a)
    return r1, r2

In [37]:
raices(3,1,-5)

(1.135041612651109, -1.4683749459844424)

In [53]:
import numpy as np
import math
def raices(a,b,c):
    raices=np.poly1d([a,b,c])
    return raices.r

In [54]:
raices(1,2,3)

array([-1.+1.41421356j, -1.-1.41421356j])

# EJERCICIO 2

In [42]:
a=['f','o','s','o','y']
c=a.copy()
print(c)
a.reverse()
d=a.copy()
print(d)

['f', 'o', 's', 'o', 'y']
['y', 'o', 's', 'o', 'f']


In [43]:
c

['f', 'o', 's', 'o', 'y']

In [44]:
d

['y', 'o', 's', 'o', 'f']

In [51]:
def text(x):
    y=x.copy()#Saco una copia de la variable x, porque si lo hago con y=x, cuando modefique x, modifica y.
    print(y)
    x.reverse()
    z=x.copy()
    print(z)
    if y==z:
        print('La palabra ingresada es un palíndromo')
    else:
        print('No es un palíndromo')
    return

In [53]:
text(['f','o','s','o','y'])

['f', 'o', 's', 'o', 'y']
['y', 'o', 's', 'o', 'f']
No es un palíndromo


# OTRO METODO PARA REALIZAR EL REVERSO

In [41]:
seqString = 'geeks'
print(list(reversed(seqString))) 

['s', 'k', 'e', 'e', 'g']


# EJERCICIO 3

In [56]:
import math
raices = {"1":math.sqrt(1),
          "2":math.sqrt(2),
          "3":math.sqrt(3),
          "4":math.sqrt(4),
          "5":math.sqrt(5),
          "6":math.sqrt(6),
          "7":math.sqrt(7),
          "8":math.sqrt(8),
          "9":math.sqrt(9),
          "10":math.sqrt(10),
         }

In [57]:
raices

{'1': 1.0,
 '2': 1.4142135623730951,
 '3': 1.7320508075688772,
 '4': 2.0,
 '5': 2.23606797749979,
 '6': 2.449489742783178,
 '7': 2.6457513110645907,
 '8': 2.8284271247461903,
 '9': 3.0,
 '10': 3.1622776601683795}

# EJERCICIO 4

In [72]:
cm = {"a":".-",
      "b":"-...", 
      "c":"-.-.",
      "d":"-..",
      "e":".",
      "f":"..-.",
      "g":"--.",
      "h":"....",
      "i":"..",
      "j":".---",
      "k":"-.-",
      "l":".-..",
      "m":"--",
      "n":"-.",
      "o":"---",
      "p":".--.",
      "q":"--.-",
      "r":".-.",
      "s":"...",
      "t":"-",
      "u":"..-",
      "v":"...-",
      "w":".--",
      "x":"-..-",
      "y":"-.--",
      "z":"--..",
     }

In [110]:
a=input("Ingrese una palabra a convertir en Morse : ")
b=list(a)

Ingrese una palabra a convertir en Morse : hola


In [84]:
b

['h', 'o', 'l', 'a']

In [96]:
c=list(cm)

In [106]:
cm["a"]

'.-'

In [97]:
b[3]==c[0]

True

In [111]:
for clave1 in b:
    print(clave1)
    for clave2 in c:
        if clave1==clave2:
            print(cm[clave1])

h
....
o
---
l
.-..
a
.-


In [108]:
a=input("Ingrese una palabra a convertir en Morse : ")
b=list(a)
c=list(cm)# Transformo un diccionario en lista para poder comparar entre listas
for clave1 in b: #Bucle para recorrer la lista b. Cada elemento de b se almacena en la variable clave1.
    print(clave1)
    for clave2 in c: # Bucle para recorrer la lista c. Cada elemento de b se almacena en la variable clave2.
        if clave1==clave2: #Comparo clave1 y clave2 que contienen los elementos de las listas b y c.
            print(cm[clave1]) #Cuando sean iguales, imprimo la clave del diccionario cm.

Ingrese una palabra a convertir en Morse : cadena
c
-.-.
a
.-
d
-..
e
.
n
-.
a
.-


In [128]:
def dic(x,y):
    u=list(x)
    v=list(y)
    print("Las claves del primer diccionario es:")
    for clave1 in u:
        print(x[clave1])
    print("Las claves del segundo diccionario es")
    for clave2 in v:
        print(y[clave2])

In [126]:
x={"a":1,"b":2,"c":3,"d":4}
y={"aa":2,"ab":3,"ac":5,"ad":7,"ae":11}

In [117]:
x

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [118]:
y

{'aa': 2, 'ab': 3, 'ac': 5, 'ad': 7, 'ae': 11}

In [129]:
dic(x,y)

Las claves del primer diccionario es:
1
2
3
4
Las claves del segundo diccionario es
2
3
5
7
11


# EJERCICIO 7

In [11]:
def prime(y):
    import numpy as np
    import math
    o=np.arange(y)
    q=np.arange(y)
    print(o)
    for x in o:
        r2=math.fmod(y,x+1)
        print(r2)
        q[x]=r2
    print(q)

In [12]:
prime(5)

[0 1 2 3 4]
0.0
1.0
2.0
1.0
0.0
[0 1 2 1 0]


In [210]:
q

array([1, 2, 3])

In [76]:
import numpy as np
import math
y=4
o=np.arange(y)
q=np.arange(y)
print(o)
for x in o:
        print(x)
        q[x]=x+1
print(q)

[0 1 2 3]
0
1
2
3
[1 2 3 4]


In [84]:
q[0:4]

array([1, 2, 3, 4])

In [285]:
def primo(y):
    import numpy as np
    import math
    o=np.arange(y)
    
    print("Se crea el vector o:")
    print(o+1)
    q=np.arange(y)
    
    for x in o:
        r2=math.fmod(y,x+1)
        q[x]=r2
    
    print("Se crea un vector q con los residuos que resultan de la división del número ingresado y el vector o:")
    print(q)
    
    m=q[1:y-1]
    print("Se crea un vector m con los residuos del número ingresado y el vector o (Excepto para el 1 y si mismo):")
    print(m)
    n=len(m)
    s=np.arange(n)
    
    count=0
    for z in s:
        if m[z]==0:
            count=count+1 #Cuento cuantas veces hay un cero.
    print("")
    print("La cantidad de numeros divisibles para el número ingresado es: %s"%count)
    print("")
    if count!=0:
        print("El número ingresado no es un numero primo")
    else:
        print("El número ingresado es un numero primo")

In [287]:
primo(123)

Se crea el vector o:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123]
Se crea un vector q con los residuos que resultan de la división del número ingresado y el vector o:
[ 0  1  0  3  3  3  4  3  6  3  2  3  6 11  3 11  4 15  9  3 18 13  8  3
 23 19 15 11  7  3 30 27 24 21 18 15 12  9  6  3  0 39 37 35 33 31 29 27
 25 23 21 19 17 15 13 11  9  7  5  3  1 61 60 59 58 57 56 55 54 53 52 51
 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]
Se

In [198]:
for val in "string":
    print(hola)

NameError: name 'hola' is not defined

In [199]:
print("Comienzo")
for i in [3,4,5]:
    print("Hola ", end="")
print()
print("Final")

Comienzo
Hola Hola Hola 
Final


In [195]:
print("Comienzo")
for i in [1, 1, 1]:
    print("Hola ", end="")
print()
print("Final")

Comienzo
Hola Hola Hola 
Final


# EJERCICIO 7

In [3]:
for i in "AMIGO":
    print(f"Dame una {i}")
print("¡AMIGO!")

Dame una A
Dame una M
Dame una I
Dame una G
Dame una O
¡AMIGO!


In [18]:
f1=input("Ingresa una frase: ")
f2=f1.upper()#Transforma las palabras minusculas en mayusculas.
for i in f2:
    print(i)

Ingresa una frase: hola
H
O
L
A


In [8]:
frase

'Hola'

# EJERCICIO 8

In [23]:
def mcd(x,y):
    import math
    a=math.gcd(x,y)
    print("El maximo comun divisor de dos numeros enteros es: %s"%a)

In [24]:
mcd(48,60)

El maximo comun divisor de dos numeros enteros es: 12


# EJERCICIO 9

In [57]:
def cifrar():
    x=input("INGRESAR UNA FRASE O PALABRA EN MAYUSCULAS:")
    a="ABCDEFGHIJKLMNOPQRSTUVWXYZ" #Cadena de caracteres. Abecedario
    b="DEFGHIJKLMNOPQRSTUVWXYZABC" #Codificación de cada letra del Abecedario
    L1=dict(zip(a,b)) #Formación en un diccionario
    for i in x:
        print("La letra ingresada fue: %s"%i)
        for k in a:
            if i==k:
                print("La letra cifrada es: %s"%L1[i])
                print("")

In [58]:
cifrar()

INGRESAR UNA FRASE O PALABRA EN MAYUSCULAS:HOLA
La letra ingresada fue: H
La letra cifrada es: K

La letra ingresada fue: O
La letra cifrada es: R

La letra ingresada fue: L
La letra cifrada es: O

La letra ingresada fue: A
La letra cifrada es: D



In [28]:
L1=dict(zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ","DEFGHIJKLMNOPQRSTUVWXYZABC"))

In [29]:
L1

{'A': 'D',
 'B': 'E',
 'C': 'F',
 'D': 'G',
 'E': 'H',
 'F': 'I',
 'G': 'J',
 'H': 'K',
 'I': 'L',
 'J': 'M',
 'K': 'N',
 'L': 'O',
 'M': 'P',
 'N': 'Q',
 'O': 'R',
 'P': 'S',
 'Q': 'T',
 'R': 'U',
 'S': 'V',
 'T': 'W',
 'U': 'X',
 'V': 'Y',
 'W': 'Z',
 'X': 'A',
 'Y': 'B',
 'Z': 'C'}

In [44]:
x="HOLA"
a="ABCDEFGHIJKLMNOPQRSTUVWXYZ" #Cadena de caracteres. Abecedario
b="DEFGHIJKLMNOPQRSTUVWXYZABC" #Codificación de cada letra del Abecedario
L1=dict(zip(a,b)) #Formación en un diccionario
for i in x:
    print("La letra ingresada fue: %s"%i)
    for k in a:
        if i==k:
            print("La letra cifrada es: %s"%L1[i])
            print("")

La letra ingresada fue: H
La letra cifrada es: K

La letra ingresada fue: O
La letra cifrada es: R

La letra ingresada fue: L
La letra cifrada es: O

La letra ingresada fue: A
La letra cifrada es: D



In [38]:
L1["A"]

'D'

# EJERCICIO 10

In [236]:
import numpy as np
import operator # Libreria para trabajar con el metodo sorted.
L1=["JUAN","ARAGON","CHRISTIAN","MAXIMO"]
x=np.arange(4)
cuenta1=0
for i in L1: # guardo los nombres en la variable i
    print("El nombre de la lista es:%s"%i)
    
    a=list(i)# Para poder usar objetos, hay que convertir el strig en lista
    a.sort() #Metodo que ordena caracteres
    st="" #Defino un string vacio
    b=st.join(a) #Metodo que transforma a string una lista
    print("El nombre ordenado por letras es:%s"%b)
    
    a.reverse() #Metodo reversa
    st=""
    b=st.join(a)
    print("El nombre alfabeticamente en reversa es:%s"%b)
    
    cuenta1=cuenta1+1 #Contar el numero de elemntos de la lista L1
    
    cuenta2 = 0
    for k in i: 
        cuenta2=cuenta2+1 #contar los caractares de cada nombre de la lista L1
    
    x[cuenta1-1]=cuenta2 #Asigno al vector x el nuemro de caracteres de cada nombre



D1=dict(zip(L1,x))
print("El diccionario original es:")
print(D1)

D2=sorted(D1.items(),key=operator.itemgetter(1))
print("El diccionario ordenado por cantidad de caractaeres es:")
print(D2)

    

El nombre de la lista es:JUAN
El nombre ordenado por letras es:AJNU
El nombre alfabeticamente en reversa es:UNJA
El nombre de la lista es:ARAGON
El nombre ordenado por letras es:AAGNOR
El nombre alfabeticamente en reversa es:RONGAA
El nombre de la lista es:CHRISTIAN
El nombre ordenado por letras es:ACHIINRST
El nombre alfabeticamente en reversa es:TSRNIIHCA
El nombre de la lista es:MAXIMO
El nombre ordenado por letras es:AIMMOX
El nombre alfabeticamente en reversa es:XOMMIA
El diccionario original es:
{'JUAN': 4, 'ARAGON': 6, 'CHRISTIAN': 9, 'MAXIMO': 6}
El diccionario ordenado por cantidad de caractaeres es:
[('JUAN', 4), ('ARAGON', 6), ('MAXIMO', 6), ('CHRISTIAN', 9)]


[('JUAN', 4), ('ARAGON', 6), ('MAXIMO', 6), ('CHRISTIAN', 9)]

In [120]:
import numpy as np
np.arange(10)+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:

L2=list("JUAN")
print(L2)
L2.sort()
print(L2)
s=""
a=s.join(L2)
print(a)
count=0
for i in "JUAN":
    count=count+1
print(count)

['J', 'U', 'A', 'N']
['A', 'J', 'N', 'U']
AJNU
4


In [133]:
a

'AJNU'

In [93]:
s=""
s.join(L2)

'AJNU'

In [167]:
L3=[1,2,3]
c=np.arange(4)
c[0]=5

In [162]:
c

array([0, 1, 2, 3])

In [169]:
c

array([5, 1, 2, 3])

In [193]:
c=np.zeros((1,4))

In [194]:
np.ravel(c)

array([0., 0., 0., 0.])

In [195]:
c=np.arange(4)

In [196]:
c

array([0, 1, 2, 3])